# Generated by Django 3.2.7 on 2021-10-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.TextField()),
                ('price', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(upload_to='cars')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
